spring:
  application:
    name: costpilot-backend
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
